
--
-- Sqlite SQL Schema dump automatic generated by geni
--

CREATE TABLE d1_migrations(
		id         INTEGER PRIMARY KEY AUTOINCREMENT,
		name       TEXT UNIQUE,
		applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE _cf_METADATA (
        key INTEGER PRIMARY KEY,
        value BLOB
      );
CREATE TABLE `keys` (
	`id` text PRIMARY KEY NOT NULL,
	`key` text NOT NULL,
	`provider` text NOT NULL,
	`model_coolings` text,
	`total_cooling_seconds` integer DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'active' NOT NULL,
	`created_at` integer DEFAULT (strftime('%s', 'now')) NOT NULL,
	`updated_at` integer DEFAULT (strftime('%s', 'now')) NOT NULL
);
CREATE UNIQUE INDEX `provider_key_unq_idx` ON `keys` (`provider`,`key`);
CREATE INDEX `provider_status_created_at_idx` ON `keys` (`provider`,`status`,`created_at`);
CREATE INDEX `total_cooling_seconds_idx` ON `keys` (`total_cooling_seconds`);
CREATE TABLE schema_migrations (id VARCHAR(255) PRIMARY KEY);